name: KoalaKraftCrystals
version: ${project.version}
main: net.obesephoenix.koalakraftcrystals.KoalaKraftCrystals
api-version: 1.17
authors: [ Obesephoenix ]
description: A private plugin that adds custom crystals to the KoalaKraft SMP!
commands:
  kkc:
    description: The central KoalaKraftCrystals command!
    usage: /kkc <args>
permissions:
  koalakraftcrystals.*:
    description: Gives permission to all KKC commands!
    children:
      koalakraftcrystals.givecrystal: true
      koalakraftcyrstals.crystalinfo: true
  koalakraftcrystals.givecrystal:
    description: Gives permission to use /kkc givecrystal!
    default: op
  koalakraftcrystals.crystalinfo:
    description: Gives permission to use /kkc crystalinfo!
    default: op
  koalakraftcrystals.disablecrystal:
    description: Gives permission to use /kkc disablecrystal!
    default: op
  koalakraftcrystals.default:
    default: true
